# Generated by Django 5.1.1 on 2024-09-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_descriptions',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
