# Generated by Django 5.1.1 on 2024-09-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_product_product_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_descriptions',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
