# Generated by Django 5.1.1 on 2024-10-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_product_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_after_discount',
            field=models.IntegerField(null=True),
        ),
    ]
