# Generated by Django 5.1.2 on 2024-10-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_in_rials',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_after_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slugname',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
