# Generated by Django 5.1.1 on 2024-09-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_rename_user_comment_owner_alter_comment_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Owner',
            new_name='owner',
        ),
    ]
