# Generated by Django 5.1.1 on 2024-10-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_orderproduct'),
        ('product_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='product_app.product'),
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
