# Generated by Django 5.1.1 on 2024-10-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_alter_order_products_delete_orderproduct'),
        ('product_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='product_app.product'),
        ),
    ]
